version: "3.8"

volumes:
  dronevolume:
    name: drone-volume

networks:
  dronenetwork:
    name: drone-network

services:
  elasticsearch:
    container_name: drone-es
    image: docker.elastic.co/elasticsearch/elasticsearch:8.0.1
    environment:
      - "xpack.security.enabled=false"
      - "discovery.type=single-node"
    networks:
      - dronenetwork
    ports:
      - "9200:9200"

  kibana:
    container_name: drone-kb
    image: docker.elastic.co/kibana/kibana:8.0.1
    environment:
      - ELASTICSEARCH_HOSTS=http://drone-es:9200
    networks:
      - dronenetwork
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"